//Backend/authController.js
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const pool = require("./db");

const signup = async (req, res) => {
  const connection = await pool.getConnection();
  try {
    await connection.beginTransaction();

    const data = req.body;
    console.log("Received signup data:", data);

    // Hash password
    const passwordHash = await bcrypt.hash(data.password, 10);

    // **INSERT user - TRIGGER auto-generates user_id (C00001, T00001)**
    const [userResult] = await connection.execute(
      `INSERT INTO users (role, phone, email, password_hash) 
       VALUES (?, ?, ?, ?)`,
      [data.role, data.phone, data.email, passwordHash],
    );

    // **Get the auto-generated user_id from LAST_INSERT_ID()**
    const [idResult] = await connection.execute(
      "SELECT LAST_INSERT_ID() as lastId",
    );
    const numericId = idResult[0].lastId;

    // **Get the actual VARCHAR user_id generated by trigger**
    const [userRows] = await connection.execute(
      "SELECT user_id FROM users WHERE role = ? AND phone = ? ORDER BY created_at DESC LIMIT 1",
      [data.role, data.phone],
    );

    const userId = userRows[0]?.user_id;

    if (!userId) {
      throw new Error("Failed to generate user_id - check database triggers");
    }

    console.log("✅ New user created:", { userId, numericId });

    // **TRIGGER already created profile row - just UPDATE it**
    if (data.role === "customer") {
      await connection.execute(
        `UPDATE customer_profile 
         SET customer_name = ?, house_no = ?, street = ?, area = ?, 
             district = ?, state = ?, country = ?, pincode = ?
         WHERE customer_id = ?`,
        [
          data.fullName,
          data.house_no,
          data.street,
          data.area,
          data.district || "Tamil Nadu",
          data.state || "Tamil Nadu",
          data.country || "India",
          data.pincode || "",
          userId,
        ],
      );
    } else {
      await connection.execute(
        `UPDATE tailor_shop_profile 
         SET tailor_name = ?, shop_name = ?, house_no = ?, street = ?, area = ?,
             district = ?, state = ?, country = ?, pincode = ?
         WHERE tailor_id = ?`,
        [
          data.fullName,
          `${data.fullName}'s Shop`,
          data.house_no,
          data.street,
          data.area,
          data.district || "Tamil Nadu",
          data.state || "Tamil Nadu",
          data.country || "India",
          data.pincode || "",
          userId,
        ],
      );
    }

    await connection.commit();

    // Generate JWT with VARCHAR user_id
    const token = jwt.sign(
      { userId, role: data.role }, // userId is now "C00001", "T00001"
      process.env.JWT_SECRET,
      { expiresIn: "7d" },
    );

    res.json({
      success: true,
      message: "User created successfully!",
      userId, // Returns "C00001", "T00001"
      role: data.role,
      token,
    });
  } catch (error) {
    await connection.rollback();
    console.error("Signup error:", error);
    res.status(400).json({
      success: false,
      error: error.message.includes("already exists")
        ? "Phone/Email already registered for this role"
        : error.message,
    });
  } finally {
    connection.release();
  }
};

const verifyOtp = async (req, res) => {
  try {
    const { phone, otp } = req.body;

    // TODO: Implement real OTP verification from Redis/cache
    const validOtp = "123456";

    if (otp === validOtp) {
      res.json({ success: true, verified: true });
    } else {
      res.status(400).json({ success: false, error: "Invalid OTP" });
    }
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

const checkPhoneExists = async (req, res) => {
  try {
    const { phone, role } = req.body;

    const [rows] = await pool.execute(
      `SELECT user_id FROM users 
       WHERE phone = ? AND role = ?`,
      [phone, role],
    );

    const exists = rows.length > 0;
    res.json({ exists, userId: exists ? rows[0].user_id : null });
  } catch (error) {
    console.error("Phone check error:", error);
    res.status(500).json({ success: false, error: "Phone check failed" });
  }
};

const login = async (req, res) => {
  try {
    const { phone, password, role } = req.body;

    const [rows] = await pool.execute(
      `SELECT user_id, role, password_hash 
       FROM users 
       WHERE phone = ? AND role = ?`,
      [phone, role],
    );

    if (rows.length === 0) {
      return res
        .status(401)
        .json({ success: false, error: "Invalid credentials" });
    }

    const user = rows[0];
    const isValidPassword = await bcrypt.compare(password, user.password_hash);

    if (!isValidPassword) {
      return res
        .status(401)
        .json({ success: false, error: "Invalid credentials" });
    }

    const token = jwt.sign(
      { userId: user.user_id, role: user.role },
      process.env.JWT_SECRET,
      { expiresIn: "7d" },
    );

    res.json({
      success: true,
      userId: user.user_id,
      role: user.role,
      token,
    });
  } catch (error) {
    console.error("Login error:", error);
    res.status(500).json({ success: false, error: "Login failed" });
  }
};

module.exports = {
  signup,
  checkPhoneExists,
  verifyOtp,
  login,
};
